Repository NadavKtalav11/The-Market, pull requests merged in 2024-07, with the labels that each got.

#512 notifications test
  src/main/java/DomainLayer/Market/Market.java
  src/main/java/DomainLayer/Notifications/LateNotificationFacade.java
  src/main/java/PresentationLayer/Vaadin/MyWebSocketHandler.java
Labels: high priority

#513 fixing tests
  src/main/java/DomainLayer/Market/Market.java
  src/main/java/DomainLayer/PaymentServices/PaymentServicesFacade.java
  src/main/java/DomainLayer/SupplyServices/ShiftingDetails.java
  src/main/java/DomainLayer/User/UserFacade.java
  src/main/java/PresentationLayer/WAF/Service_layer.java
  src/main/resources/stateAfterInit.yaml
  src/test/java/AcceptanceTests/System/AddingExternalPaymentServices.java
  src/test/java/AcceptanceTests/System/AddingExternalSupplyServices.java
  src/test/java/AcceptanceTests/System/Payment.java
  src/test/java/AcceptanceTests/System/Provision.java
  src/test/java/DomainLayer/System/StateInit.java
  src/test/java/DomainLayer/externalConnections.java
  target/classes/DomainLayer/Market/Market.class
  target/classes/DomainLayer/Notifications/NotificationFacade.class
  target/classes/DomainLayer/PaymentServices/PaymentServicesFacade.class
  target/classes/DomainLayer/Role/RoleFacade.class
  target/classes/DomainLayer/Store/StoreDiscountPolicy/DiscountRulesRepository.class
  target/classes/DomainLayer/Store/StorePurchasePolicy/Purchase.class
  target/classes/DomainLayer/Store/StorePurchasePolicy/PurchaseRulesRepository.class
  target/classes/DomainLayer/SupplyServices/ShiftingDetails.class
  target/classes/DomainLayer/User/UserFacade.class
  target/classes/DomainLayer/User/UserMemoryRepository.class
  target/classes/PresentationLayer/Vaadin/StompPrincipal.class
  target/classes/PresentationLayer/WAF/ServerSocket$1.class
  target/classes/PresentationLayer/WAF/ServerSocket$2.class
  target/classes/PresentationLayer/WAF/ServerSocket.class
  target/classes/PresentationLayer/WAF/Service_layer.class
  target/classes/Util/Main.class
  target/classes/stateAfterInit.yaml
  target/test-classes/AcceptanceTests/System/AddingExternalPaymentServices.class
  target/test-classes/AcceptanceTests/System/AddingExternalSupplyServices.class
  target/test-classes/AcceptanceTests/System/Payment.class
  target/test-classes/AcceptanceTests/System/Provision.class
  target/test-classes/DomainLayer/Store/DiscountPolicy/DiscountRulesRepositoryTest.class
  target/test-classes/DomainLayer/Store/PurchasePolicyTest.class
  target/test-classes/DomainLayer/System/StateInit.class
  target/test-classes/DomainLayer/externalConnections.class
Labels: bug

#514 admin close store
  src/main/java/DomainLayer/Role/RoleFacade.java
Labels: high priority

#515 Notification facade
  src/main/java/DomainLayer/Market/Market.java
  src/main/java/DomainLayer/PaymentServices/ExternalPaymentService.java
  src/main/java/DomainLayer/User/Guest.java
  src/main/java/DomainLayer/User/Member.java
  src/main/java/DomainLayer/User/State.java
  src/main/java/DomainLayer/User/User.java
  src/main/java/DomainLayer/User/UserFacade.java
  src/main/java/PresentationLayer/WAF/MarketController.java
  src/main/java/PresentationLayer/WAF/Service_layer.java
Labels: high priority

#516 removed duplicated functions
  src/main/java/DomainLayer/Role/RoleFacade.java
  target/classes/DomainLayer/Market/Market.class
  target/classes/DomainLayer/Notifications/LateNotificationFacade.class
  target/classes/DomainLayer/PaymentServices/ExternalPaymentService.class
  target/classes/DomainLayer/PaymentServices/PaymentServicesFacade.class
  target/classes/DomainLayer/Role/RoleFacade.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/AgeRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/AmountRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/DateRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/PriceRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/TestRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/TimeRule.class
  target/classes/DomainLayer/Store/Store.class
  target/classes/DomainLayer/Store/StoreDiscountPolicy/SimpleDiscountValue.class
  target/classes/DomainLayer/SupplyServices/ShiftingDetails.class
  target/classes/DomainLayer/User/Guest.class
  target/classes/DomainLayer/User/Member.class
  target/classes/DomainLayer/User/State.class
  target/classes/DomainLayer/User/User.class
  target/classes/DomainLayer/User/UserFacade.class
  target/classes/PresentationLayer/Vaadin/MyWebSocketHandler.class
  target/classes/PresentationLayer/WAF/MarketController$1.class
  target/classes/PresentationLayer/WAF/MarketController$2.class
  target/classes/PresentationLayer/WAF/MarketController.class
  target/classes/PresentationLayer/WAF/Service_layer.class
  target/classes/Util/DiscountValueDTO.class
Labels: bug

#519 git ignore
  .gitignore
Labels: low priority

#520 checks if the payment succeded, if not, not created aquacition
  src/main/java/DomainLayer/Market/Market.java
  src/main/java/Util/ExceptionsEnum.java
  src/test/java/DomainLayer/externalConnections.java
  target/classes/DomainLayer/Market/Market.class
  target/classes/DomainLayer/Notifications/LateNotificationFacade.class
  target/classes/DomainLayer/PaymentServices/ExternalPaymentService.class
  target/classes/DomainLayer/PaymentServices/PaymentServicesFacade.class
  target/classes/DomainLayer/Role/RoleFacade.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/AgeRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/AmountRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/DateRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/PriceRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/SimpleRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/TestRule.class
  target/classes/DomainLayer/Store/PoliciesRulesLogicalConditions/TimeRule.class
  target/classes/DomainLayer/Store/Store.class
  target/classes/DomainLayer/Store/StoreDiscountPolicy/SimpleDiscountValue.class
  target/classes/DomainLayer/SupplyServices/ShiftingDetails.class
  target/classes/DomainLayer/User/Guest.class
  target/classes/DomainLayer/User/Member.class
  target/classes/DomainLayer/User/State.class
  target/classes/DomainLayer/User/User.class
  target/classes/DomainLayer/User/UserFacade.class
  target/classes/PresentationLayer/Vaadin/MyWebSocketHandler.class
  target/classes/PresentationLayer/WAF/MarketController$1.class
  target/classes/PresentationLayer/WAF/MarketController$2.class
  target/classes/PresentationLayer/WAF/MarketController$3.class
  target/classes/PresentationLayer/WAF/MarketController$4.class
  target/classes/PresentationLayer/WAF/MarketController$5.class
  target/classes/PresentationLayer/WAF/MarketController$6.class
  target/classes/PresentationLayer/WAF/MarketController$7.class
  target/classes/PresentationLayer/WAF/MarketController$8.class
  target/classes/PresentationLayer/WAF/MarketController.class
  target/classes/PresentationLayer/WAF/Service_layer.class
  target/classes/Util/DiscountValueDTO.class
  target/classes/Util/ExceptionsEnum$64.class
  target/classes/Util/ExceptionsEnum$65.class
  target/classes/Util/ExceptionsEnum$66.class
  target/classes/Util/ExceptionsEnum$67.class
  target/classes/Util/ExceptionsEnum$68.class
  target/classes/Util/ExceptionsEnum$69.class
  target/classes/Util/ExceptionsEnum$70.class
  target/classes/Util/ExceptionsEnum$71.class
  target/classes/Util/ExceptionsEnum.class
  target/test-classes/DomainLayer/Store/LogicalConditions/AgeRuleTest.class
  target/test-classes/DomainLayer/Store/LogicalConditions/AmountRuleTest.class
  target/test-classes/DomainLayer/Store/LogicalConditions/DateRuleTest.class
  target/test-classes/DomainLayer/Store/LogicalConditions/PriceRuleTest.class
  target/test-classes/DomainLayer/Store/LogicalConditions/TimeRuleTest.class
  target/test-classes/DomainLayer/externalConnections.class
Labels: bug
